services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --log-file -
    rootDir: backend
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: airbnb-db
          property: connectionString

databases:
  - name: airbnb-db
    plan: free
    databaseName: airbnb
    user: airbnb
